### ISSUE TITLE
Plugin-error bij QGIS 3.16.5 (x64)

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/QGIS_project#125]
```
Kon plug-in 'oiv' niet laden wegens een fout bij het aanroepen van de methode classFactory() 

AttributeError: module 'qgis.PyQt' has no attribute 'uic' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins\oiv\__init__.py", line 34, in classFactory
    from .oiv import oiv
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins\oiv\oiv.py", line 16, in 
    import oiv.oiv_base_widget as OB
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins\oiv\oiv_base_widget.py", line 14, in 
    import oiv.bag_pand.oiv_pandgegevens as OPG
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins\oiv\bag_pand\oiv_pandgegevens.py", line 12, in 
    import oiv.tools.stackwidget as SW
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins\oiv\tools\stackwidget.py", line 12, in 
    FORM_CLASS, _ = PQt.uic.loadUiType(os.path.join(
AttributeError: module 'qgis.PyQt' has no attribute 'uic'


Python versie: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS versie: 3.16.5-Hannover Hannover, 58ba7c1ed6 

Python pad:
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python
C:/Users/<username>/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/<username>/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.16\apps\Python37
C:\PROGRA~1\QGIS3~1.16\apps\Python37\Scripts
C:\PROGRA~1\QGIS3~1.16\bin\python37.zip
C:\PROGRA~1\QGIS3~1.16\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib
C:\PROGRA~1\QGIS3~1.16\bin
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\Pythonwin
C:/Users/<username>/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/ProgramData/OIV-3.3.1
```

Versie-info:

QGIS-versie: 3.16.5-Hannover
QGIS code revisie: 58ba7c1ed6
Gecompileerd tegen Qt: 5.11.2
Gebruikt nu Qt: 5.11.2
Gecompileerd tegen GDAL/OGR: 3.1.4
Gebruikt nu GDAL/OGR: 3.1.4
Gecompileerd tegen GEOS: 3.8.1-CAPI-1.13.3
Gebruikt nu GEOS: 3.8.1-CAPI-1.13.3
Gecompileerd tegen SQLite: 3.29.0
Uitgevoerd met SQLite: 3.29.0
PostgreSQL Client Versie: 11.5
SpatiaLite-versie: 4.3.0
QWT versie: 6.1.3
QScintilla2 Versie: 2.10.8
Gecompileerd tegen PROJ: 6.3.2
Gebruikt nu PROJ: Rel. 6.3.2, May 1st, 2020
Versie OS: Windows 10 (10.0)
Actieve plug-ins van Python: pdokservicesplugin; db_manager; processing;

**Comment by ghost** [comment]
Probleem speelt nu wanneer QGIS voor het eerst is gestart. Zodra je in QGIS zit, kan je via het plugins-menu de OIV-plugin deselecteren en opnieuw selecteren, dan functioneert het wel.

**Comment by ghost** [comment]
Probleem speelt nu niet meer. 3.3.2 plugin geinstalleerd, icm een fresh install van QGIS 3.16.5. Kan wat ons betreft dus gesloten worden.
