### ISSUE TITLE
Fout bij opslaan configuratie

### ISSUE THREAD

**Issue by ghost** [OIV-NL-QGIS/QGIS_project#95]
Bij het wijzigen van de BAG databron in het configuratiescherm de onderstaande melding bij het opslaan:

```
io.UnsupportedOperation: not readable 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins\oiv\oiv_config.py", line 26, in 
    self.save.clicked.connect(lambda dummy=None, saveConfig=True: self.close_config(dummy, saveConfig))
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins\oiv\oiv_config.py", line 58, in close_config
    write_plugin_settings("BAGCONNECTION", self.data)
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins\oiv\helpers\constants.py", line 17, in write_plugin_settings
    data = json.load(f)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
io.UnsupportedOperation: not readable
```

**Comment by ghost** [comment]
_Achtergrondinfo:_
QGIS-versie: 3.10.13-A Coruña
QGIS code revisie: 311f3bbade
Gecompileerd tegen Qt: 5.11.2
Gebruikt nu Qt: 5.11.2
Gecompileerd tegen GDAL/OGR: 3.1.4
Gebruikt nu GDAL/OGR: 3.1.4
Gecompileerd tegen GEOS: 3.8.1-CAPI-1.13.3
Gebruikt nu GEOS: 3.8.1-CAPI-1.13.3
Gecompileerd tegen SQLite: 3.29.0
Uitgevoerd met SQLite: 3.29.0
PostgreSQL Client Versie: 11.5
SpatiaLite-versie: 4.3.0
QWT versie: 6.1.3
QScintilla2 Versie: 2.10.8
Gecompileerd tegen PROJ: 6.3.2
Gebruikt nu PROJ: Rel. 6.3.2, May 1st, 2020
Versie OS: Windows 10 (10.0)
Actieve plug-ins van Python: pdokservicesplugin; db_manager; MetaSearch; oiv; processing
Python-versie: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]

**Comment by ghost** [comment]
Zojuist opnieuw gekeken naar het issue, en vermoedde mogelijk een rechten-probleem. Hele installatiemap `(C:\ProgramData\OIV-3.3.0)` is nu voor alle gebruikers te lezen en te schrijven. Voor de zekerheid nog een map  `config_files` aangemaakt (zoals [hier ](https://github.com/OIV-NL-QGIS/OIV_project/blob/v.3.3.0/plugin/oiv/helpers/constants.py#L15)naar wordt gerefereerd). 

Dit gaf het volgende resultaat:
```
2021-02-22T15:24:47     WARNING    Traceback (most recent call last):
              File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins\oiv\__init__.py", line 34, in classFactory
              from .oiv import oiv
              File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins\oiv\oiv.py", line 16, in 
              import oiv.oiv_base_widget as OB
              File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins\oiv\oiv_base_widget.py", line 9, in 
              import oiv.tools.filter_object as FO
              File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins\oiv\tools\filter_object.py", line 5, in 
              import oiv.helpers.drawing_helper as DH
              File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins\oiv\helpers\drawing_helper.py", line 10, in 
              BLSNAPLAYERS = [PC.PAND["bouwlaaglayername"], PC.bagpand_layername(), "Bouwkundige veiligheidsvoorzieningen", "Ruimten"]
              File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins\oiv\helpers\constants.py", line 22, in bagpand_layername
              baglayerName = PAND["bagpandlayername"] + plugin_settings("BAGCONNECTION")["active"]
              File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins\oiv\helpers\constants.py", line 9, in plugin_settings
              data = json.load(f)
              File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\json\__init__.py", line 296, in load
              parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
              File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\json\__init__.py", line 348, in loads
              return _default_decoder.decode(s)
              File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\json\decoder.py", line 337, in decode
              obj, end = self.raw_decode(s, idx=_w(s, 0).end())
              File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\json\decoder.py", line 355, in raw_decode
              raise JSONDecodeError("Expecting value", s, err.value) from None
             json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)    
```

**Comment by Oostjoost** [comment]
Was inderdaad een rechten probleem.

Voor het opslaan van de configuratie was het nodig om tijdens de installatie QGis/OIV rechten te geven op de plugin_settings.json.
Ik heb de release aangepast, i.o.m. OIV werkgroep blijft et wel dezelfde versie.

**Comment by Oostjoost** [comment]
Helaas nog niet opgelost. Ik zorg met 30 min voor een wel werkende versie.
